### ISSUE TITLE
Checkpoint 03

### ISSUE THREAD

**Issue by Carlos-Leon98** [Carlos-Leon98/Inventory-Management-System#6]
Good afternoon @pawaitemadisoncollege,

My application is ready for checkpoint 03, AWS URL is in the student repository, if there is any feedback, please, let me know.

link: https://github.com/mad-ent-java-s24/student/blob/main/IndividualProjects.md

Sorry for all this delay, I am working to be on date with all activities and exercises.

Thank you,
Carlos Leon Rivas

**Comment by pawaitemadisoncollege** [comment]
HI @Carlos-Leon98!

For Checkpoint 3 - I was able to login (just needed to remove the s from https and I was able to access the application). I'd say don't worry about this for now and focus instead on adding the key functionality to your application.  Time log was up-to-date as of the time you created the checkpoint 3 issue. 

- [ ] However, I was not able to see any data in the application - I tried Dashboard, Inventory, Analytics, and Orders, but none of those links showed any data. There was an error though: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection [Connections could not be acquired from the underlying database!] [n/a]
	org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:63). I realize I am reviewing this well past the date when you opened the issue, so maybe this was working and has since been redeployed with a possible bug? 

- [ ] Is your project plan up-to-date?  Nothing is checked off past week 7. 

I poked around in some of the code, too:

- [ ] I noticed some hard-coded values in the jsps, such as, https://github.com/Carlos-Leon98/Inventory-Management-System/blob/6e9d20c9787f72db031ec55f1747cf094aadf528/src/main/webapp/addProduct.jsp#L40-L44 and https://github.com/Carlos-Leon98/Inventory-Management-System/blob/6e9d20c9787f72db031ec55f1747cf094aadf528/src/main/webapp/editProduct.jsp#L41-L46, for example. Can these be populated from the database instead so that they are meaningful values?

**Comment by Carlos-Leon98** [comment]
Hi @pawaitemadisoncollege thank you for your feedback.

- [ ] However, I was not able to see any data in the application - I tried Dashboard, Inventory, Analytics, and Orders, but none of those links showed any data. There was an error though: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection [Connections could not be acquired from the underlying database!] [n/a]
org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:63). I realize I am reviewing this well past the date when you opened the issue, so maybe this was working and has since been redeployed with a possible bug? The root cause was: java.sql.SQLException: Access denied for user 'student'@'172.31.43.189' (using password: YES)


Related to this point, it is weird I didn't have this issue when I deployed the app and I haven't deployed any other change since then I have been working on my local machine since then, I will check this and reply to you ASAP.

- [ ] Is your project plan up-to-date? Nothing is checked off past week 7.

I haven't pushed the change related to the plan project, I even added two more user stories that I haven't pushed into my project plan. I will update it ASAP.


- [ ] And related to the third point. Honestly, I forgot to work on that part. If you see this part of my code.

`
 <form action="addOrder" method="post">
            <div class="form-group">
                <label for="customerId">Customer</label>
                <select class="form-control" id="customerId" name="customerId">
                    <option value="">Select Customer</option>
                    <% for (Customer customer : (List<Customer>) request.getAttribute("customers")) { %>
                    <option value="<%= customer.getCustomerId() %>"><%= customer.getFirstName() %> <%= customer.getLastName() %></option>
                    <% } %>
                </select>
            </div>
`

In my: https://github.com/Carlos-Leon98/Inventory-Management-System/blob/main/src/main/webapp/addOrder.jsp

I set that field to pull the information from my Customer table and display all existing customers. Once I fix that part I will let you know.

Thank you,

Carlos Leon Rivas

**Comment by pawaitemadisoncollege** [comment]
HI @Carlos-Leon98 - just checking in to see if the issues above are resolved? 

Also, note that using script code here is not a best practice: https://github.com/Carlos-Leon98/Inventory-Management-System/blob/24dc9ae090de9290efcc76ac8fc9c6918557c666/src/main/webapp/addOrder.jsp#L31-L33. You should use jstl. The only place `<%.... %>` should exist in your jsps is to import the taglib.

**Comment by Carlos-Leon98** [comment]
Hi @pawaitemadisoncollege these last few days I have been mostly working on ending up the main functionality of the application. Once I finish up main main goal is to update all documentation and then, start the deployment configuration.

I don't know if this works for now or if you prefer me to focus on the issues, I can do it too.

Thank you,
Carlos Leon Rivas

**Comment by Carlos-Leon98** [comment]
Hi @pawaitemadisoncollege,

My project plan, user stories, and time logs are updated, feel free to review them. Let me know about any feedback.

Thank you, 
Carlos Leon Rivas

**Comment by Carlos-Leon98** [comment]
Good evening @pawaitemadisoncollege, 

I redeployed my app, can you confirm if you see the data displayed when clicking on "Inventory" or "Order"? 

I haven't fixed the issue with HTTP vs HTTPS yet, I am working on other issues I am getting but once I am done with those I will update the repository.

Thank you, 
Carlos Leon Rivas.

**Comment by pawaitemadisoncollege** [comment]
Yes! @Carlos-Leon98! I can see orders and the order details. Yay! I wouldn't worry about the https vs. http issue at this point.  More important is the core functionality! Your Checkpoint 3 is complete. You can close this up.

**Comment by Carlos-Leon98** [comment]
Thank you @pawaitemadisoncollege. I am closing this issue.
